compile:
	$gcc main.c -o ex2b -g -Wall -lpthread
	@echo "Finished Compiling, Ready To execute."
	@echo "To execute the program type: ./ex2b [Input File] [SourceRouter] [Number of connection attempts]"
clean:
	rm -f *.o

